#!/usr/bin/env python

import os
import os.path
import sys
import re
import getopt
import xml.etree.ElementTree as et

class SyntaxError(Exception):
  pass

TBLOCK = r'\(\(([\w][\w:]*)[ \t]*'
TCLOSE = r'\)\)'
TATTR = r"([\w][\w:.]*)=(?:\'((?:[^']|\\')*)\'|(\S+))[ \t]*"
TATTR_SINGLE = r"(\w+)[ \t]*"
TOPEN = r'\|'
TEOL = r'[ \t\r]*\n+( *)'
# Must be last.
TANY = r'(.*?)(\(\(|\)\)|\n)'
tokens = [TBLOCK, TCLOSE, TOPEN, TEOL, TANY]
attrs = [TATTR, TATTR_SINGLE]

def token(input):
  for t in tokens:
    m = re.match(t, input)
    if m is not None:
      return t, m
  return None, None

def attr(input):
  for t in attrs:
    m = re.match(t, input)
    if m is not None:
      return t, m
  return None, None

def adv(input, m, gr=0):
  if m is None:
    return input
  return input[len(m.group(gr)):]

def rew(input, m, gr=0):
  return m.group(gr) + input

def block(indent, builder, input):
  tok, m = token(input)
  if m is None or tok != TBLOCK:
    return input
  input = adv(input, m)

  tag = m.group(1)
  el = builder.start(tag, {})

  while True:
    tok, m = attr(input)
    input = adv(input, m)
    if tok is None:
      break

    if tok == TATTR:
      el.set(m.group(1), m.group(2))
    else:
      el.set(m.group(1), '')

  tok, m = token(input)
  input = adv(input, m)

  if tok == TOPEN:
    indent += 2  # Can continue on next line.
  elif tok == TEOL:
    builder.data(m.group(0))
    if len(m.group(1)) > indent:
      # Equivalent to TOPEN.
      indent = len(m.group(1))
    else:
      builder.end(tag)
      return input
  elif tok == TCLOSE:
    builder.end(tag)
    return input
  else:
    raise Exception("Unexpected token '%s': '%s'" % (tok, m.group(0)))

  while True:
    tok, m = token(input)
    if tok is None:
      break
    input = adv(input, m)

    if tok == TBLOCK:
      # Sub block.
      input = rew(input, m)
      input = block(indent, builder, input)

    elif tok == TCLOSE:
      break

    elif tok == TEOL and len(m.group(1)) < indent:
      builder.data(m.group(0))
      # Close.
      input = rew(input, m)
      break

    elif tok == TEOL:
      builder.data(m.group(0))
      # Continue content.
      continue

    elif tok == TANY:
      # Content.
      input = rew(input, m, 2)
      builder.data(m.group(1))

    else:
      raise Exception("Unexpected token '%s': '%s'" % (tok, m.group(0)))

  builder.end(tag)
  return input


re_leading_blanks = re.compile(r'^[\s\n]+', re.S)

if __name__ == '__main__':
  opts, args = getopt.getopt(sys.argv[1:], None, ['xml', 'html5'])
  opts = dict(opts)

  with open(args[0]) as f:
    input = f.read()

  builder = et.TreeBuilder()

  with open(args[1], 'w') as f:

    if '--xml' in opts:
      print>>f, '<?xml version="1.0"?>'
    elif '--html5' in opts:
      print>>f, '<!DOCTYPE html>'

    while True:
      input = re_leading_blanks.sub('', input)
      if len(input) == 0:
        break
      input = block(0, builder, input)
      root = builder.close()
      tree = et.ElementTree(root)

      tree.write(f)
      print>>f
