#!/usr/bin/env bash

for n in t/t*.nxml; do
  t=$(basename $n .nxml)
  tmp=t/result_$t.xml
  if ! ./nxml $n $tmp || ! cmp t/$t.xml $tmp; then
    err=$?
    echo "FAILED $t"
    exit $err
  fi
  rm $tmp
done
